version: "3"
services:
  db:
    image: mariadb:10.3.6
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - "./data/mysql:/var/lib/mysql"
  #app:
  #  build: .
  #  container_name: jmseg
  # command:
  #  volumes:
  #    - ".:/app"
  #  ports:
  #    - "5000:5000" # http
  #    - "5001:5001" # https
  #  links:
  #    - db